version: '3'
services:
  app:
    build: .
    ports:
      - "9003:9003"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
